Checkboxの追加
bislab-temporary/mini-hackathon-a pull request #14
Opened 2021-10-08 09:54 UTC by kacha-122

## 🔨 Details of Changes

- Checkboxを追加しました。
- Checkboxの状態によってタスクの表示が変わる機能を追加しました。

## ✅ Resolved Issues

- close #7

## 🤝 Related Issues

- #7

2021-10-08 09:58 UTC, kacha-122 commented on src/conponents/Todo.tsx
> +        {status[index] === true ? <EditablePreview as="s" /> : <EditablePreview />}
if文で書こうと思いましたがうまく動いてくれなかったので、今回は杉水氏のやり方で実装しました

2021-10-08 10:00 UTC, kacha-122 commented
セルフレビュー全然できていないと思いますが、お手すきの時間で見てアドバイスなどいただけると幸いです。

2021-10-08 12:07 UTC, watagit commented on src/conponents/Todo.tsx
> +        {status[index] === true ? <EditablePreview as="s" /> : <EditablePreview />}
![must](https://img.shields.io/badge/review-must-red)
もっと簡潔に書くのであれば、`status[index] ? <EditablePreview as="s" /> : <EditablePreview />`でいけます！
なぜかというと、`status[index]`の時点で既に boolean 型だからです 👍

2021-10-08 12:07 UTC, watagit commented on src/conponents/TodoInput.tsx
> +      onKeyPress={(e) => {
![nits](https://img.shields.io/badge/review-nits-lightgrey)
24行目の`event`と25行目の`e`はどちらも同様にイベントを表す変数なので、`event`もしくは`e`どちらかに統一すると一貫性があって読みやすくなりそうです！

2021-10-08 12:18 UTC, watagit commented on src/conponents/TodoInput.tsx
> +      onKeyPress={(e) => {
あと、型についても付けたほうが可読性上がりそうですね！
`e: KeyboardEvent<HTMLInputElement>`

[[Qiita] any型で諦めない React.EventCallback](https://qiita.com/Takepepe/items/f1ba99a7ca7e66290f24)

2021-10-08 12:52 UTC, kacha-122 commented on src/conponents/TodoInput.tsx
> +      onKeyPress={(e) => {
勉強になります👀

2021-10-08 12:53 UTC, mikiya1130 reviewed
今回の変更範囲外のレビューも含んでしまってごめんなさい。

これもそうなんですが、`TodoType` の定義は外部ファイル化すると良いかもです。(やるなら別 Issue  で)
各ファイルでタイプ定義を読み込むようにしておけば、変更への対応も1箇所の修正で済みます。
[react-study-morisaki](https://github.com/bislab-temporary/react-study-morisaki/blob/main/todo-app/src/types/TaskType.tsx) か [mini-hackathon-b](https://github.com/bislab-temporary/mini-hackathon-b/blob/main/src/types/TodoType.ts) の実装参考下さい。
```ts
// ここから
type TodoType = {
  title: string;
};
// ここまで
// 別ファイルから読み込めるように export つけてね
```

2021-10-08 12:53 UTC, mikiya1130 commented on src/conponents/Todo.tsx
>    };
![must](https://img.shields.io/badge/review-must-red)
下の方にチェック付けたタスクがある状態で削除を行うと、それ以降のタスクの打ち消し線がずれてしまいます。
また、`2番目のタスクをチェック→タスク全削除→いくつか追加` のようなことをすると、新規追加された2番目のタスクにはじめから打ち消し線が付いた状態になってしまいます。 (チェックはつかないが)
いずれも、タスク削除時に `status` の更新が上手くできていないことが原因かと思います。

2021-10-08 12:53 UTC, mikiya1130 commented on src/conponents/Todo.tsx
> +      <Checkbox align="center" w="5%" m="0 auto" onChange={() => handleStatus()} />
![must](https://img.shields.io/badge/review-must-red)
`Checkbox` に関してですが、`Flex` の子要素のセンタリングは `align="center"` ではなく、`justifyContent` かな。

![nits](https://img.shields.io/badge/review-nits-lightgrey)
あと、親の `Flex` に関して、 `align="center"` 効いてない気がします。
`margin="0 auto"` が左右センタリングなので、削除してよさそう？
また子の `Checkbox` は上述の通り `justifyContent="center"` でセンタリングできるので、`margin` の指定はいらないかも。

2021-10-08 13:08 UTC, mikiya1130 commented on src/conponents/Todo.tsx
> +        {status[index] === true ? <EditablePreview as="s" /> : <EditablePreview />}
三項演算子の方法で良いと思いますが、もし if 文を使う場合、 `return (xxx)` のところには直接書けないので、`JSX.Element` を返す関数を書くと良いと思います。

### これはできない
```tsx
<Editable defaultValue={title}>
  {
    if (status[index] === true) {
      return <EditablePreview as="s" />
    } else {
      return <EditablePreview />
    }
  }
  <EditableInput />
</Editable>
```

### 実装例
```tsx
const CustomEditablePreview = (): JSX.Element => {
  if (status[index] === true) {
    return <EditablePreview as="s" />;
  } else {
    return <EditablePreview />;
  }
};

return (
  // ---省略---
    <Editable defaultValue={title}>
      <CustomEditablePreview />
      <EditableInput />
    </Editable>
  // ---省略---
```

(という理解ですが、間違っていたら他の方ご指摘下さい。)

2021-10-08 13:18 UTC, mikiya1130 commented on src/conponents/Todo.tsx
>    };
https://user-images.githubusercontent.com/63896499/136564137-4e5aaa76-a82f-4978-b183-dd2255bf5357.mp4

2021-10-08 15:18 UTC, watagit commented on src/conponents/Todo.tsx
>    };
Todo アプリとしてこれは致命的なバグですね 👀 
@mikiya1130 このバグをイシューを作って報告してもらえますか？このままいくと、このプルリクの議論が肥大化しそうなので、別イシューで対応したいお気持ちです
@kacha-122 森崎くんがイシュー作成を通じてバグ報告をしてくれると思うので、そのイシューが作られ次第、バグの原因を調べてみてください

2021-10-08 15:36 UTC, mikiya1130 commented on src/conponents/Todo.tsx
>    };
@watagit 
対応しました。[#15](https://github.com/bislab-temporary/mini-hackathon-a/issues/15)
`Assignees` や `Label` は自分に権限なかったので付けてません。必要に応じて編集してください。

2021-10-09 10:19 UTC, watagit commented on src/conponents/TodoInput.tsx
> +type Todo = {
![must](https://img.shields.io/badge/review-must-red)
方の名前を`TodoType`に統一しましょう！

2021-10-09 10:19 UTC, watagit commented on src/conponents/TodoList.tsx
> +};
![must](https://img.shields.io/badge/review-must-red)
型の名前を`TodoType`に統一しましょう！

2021-10-09 10:23 UTC, watagit commented
@kacha-122 
念の為、やるべきことを整理しておくと、とりあえずは以下の3つに対応してみてください。対応後に再度レビュー依頼を出してください！
既知のバグや仕様変更について別イシューで対応します。

- [スタイル周りの調整](https://github.com/bislab-temporary/mini-hackathon-a/pull/14#discussion_r724976506)
- [表記の統一](https://github.com/bislab-temporary/mini-hackathon-a/pull/14#discussion_r725468094)
- [表記の統一](https://github.com/bislab-temporary/mini-hackathon-a/pull/14#discussion_r725468116)

2021-10-09 13:23 UTC, kacha-122 commented
おそらく指摘いただいた表記関連のものについてはできたと思うので確認お願いしますm(__)m

2021-10-09 13:35 UTC, watagit requested changes

2021-10-09 13:35 UTC, watagit commented on src/conponents/Todo.tsx
> +      <Checkbox justifyContent="center" w="5%" onChange={() => handleStatus()} />
![must](https://img.shields.io/badge/review-must-red)
重ねての指摘になりますが、このスタイルの部分は`justifyContent`もなくていいかもです！（手元で削除してもスタイルが変わらなかった）

また、`w="5%"`の部分はおそらくチェックボックスの右側に余白を作るために指定している？と思うのですが、右側に余白がほしいときは`margin`で指定したほうが一般的なので変更してみましょう！
今回だと`mr={2}`がぴったりな気がします（`mr`は`marginRight`の糖衣構文）

[[Chakra UI 公式] Style Props - Margin and padding](https://chakra-ui.com/docs/features/style-props#margin-and-padding)

2021-10-09 13:50 UTC, watagit approved these changes

2021-10-09 13:51 UTC, merged